# The Numpy.random package

NumPy, short for Numerical Python, is a library for numerical data analysis or scientific computing within Python. Within the NumPy package there are libraries, each one designed for analysing and manipulating data specific to the users needs. 

This NoteBook specifically deals with the Random package and should allow the reader to grasp the concept, usage and purpose of the package, while also working through examples of a number of the distributions within the Random package.


In [2]:
import numpy as np

In [3]:
x = np.random.rand(10000)
x

array([0.20156655, 0.54706445, 0.60332731, ..., 0.24093607, 0.02502729,
       0.34548886])

In [4]:
import matplotlib.pyplot as plt
plt.hist(x)

(array([1048.,  968., 1014.,  969., 1003.,  959., 1025.,  984.,  996.,
        1034.]),
 array([4.17821656e-05, 1.00028361e-01, 2.00014939e-01, 3.00001518e-01,
        3.99988096e-01, 4.99974675e-01, 5.99961253e-01, 6.99947832e-01,
        7.99934410e-01, 8.99920989e-01, 9.99907568e-01]),
 <a list of 10 Patch objects>)

In [5]:
y = np.random.uniform(10,20,100)

In [6]:
plt.hist(y)

(array([11., 14.,  9., 16., 12.,  7.,  7.,  7., 10.,  7.]),
 array([10.13314828, 11.10143367, 12.06971906, 13.03800445, 14.00628984,
        14.97457523, 15.94286062, 16.91114601, 17.8794314 , 18.84771679,
        19.81600218]),
 <a list of 10 Patch objects>)

In [13]:
z = np.random.randint(20, size=100)
plt.hist(z)

(array([ 8., 11.,  8., 13.,  7., 13., 11., 11.,  8., 10.]),
 array([ 0. ,  1.9,  3.8,  5.7,  7.6,  9.5, 11.4, 13.3, 15.2, 17.1, 19. ]),
 <a list of 10 Patch objects>)